# Generated by Django 2.1.4 on 2018-12-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='author',
            field=models.CharField(default='anonymous', max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
    ]
