# Generated by Django 2.1.4 on 2018-12-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0002_auto_20181228_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='title',
            field=models.CharField(default='My Title', max_length=255, verbose_name='Title'),
        ),
    ]
