# Generated by Django 2.1.4 on 2018-12-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0003_brick_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brick',
            options={'verbose_name': 'Wall Message', 'verbose_name_plural': 'Wall Messages'},
        ),
    ]
