# Generated by Django 2.1.4 on 2019-01-06 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thewall', '0004_auto_20181229_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brickmaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='avatar_images')),
                ('bio', tinymce.models.HTMLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Author',
                'verbose_name_plural': 'Message Authors',
            },
        ),
        migrations.AlterModelManagers(
            name='brick',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='brick',
            name='author',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to='thewall.Brickmaker'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='wall_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bricks', to='thewall.WallPage'),
        ),
    ]
