# Generated by Django 2.1.5 on 2019-01-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0005_auto_20190109_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickmaker',
            old_name='avatar',
            new_name='avatar_image',
        ),
    ]
