# Generated by Django 2.1.4 on 2019-01-07 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0005_auto_20190106_1213'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='brick',
            managers=[
            ],
        ),
    ]
