# Generated by Django 2.1.5 on 2019-01-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0006_auto_20190119_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='brick',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
