# Generated by Django 2.1.4 on 2019-01-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0006_auto_20190106_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
