# Generated by Django 2.1.5 on 2019-02-05 16:01

from django.db import migrations, models
import thewall.models


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0007_brick_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brickmaker',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to=thewall.models.user_directory_path),
        ),
    ]
