# Generated by Django 2.1.4 on 2019-01-07 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0007_auto_20190107_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_bricks', to=settings.AUTH_USER_MODEL, verbose_name='message author'),
        ),
        migrations.AlterField(
            model_name='brick',
            name='wall_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bricks', to='thewall.WallPage', verbose_name='message wall'),
        ),
        migrations.AlterField(
            model_name='brickmaker',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar_images'),
        ),
    ]
