# Generated by Django 2.1.5 on 2019-02-21 05:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0010_auto_20190213_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='brickmaker',
            name='bio',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
