# Generated by Django 2.1.5 on 2019-02-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thewall', '0011_auto_20190220_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brickmaker',
            old_name='bio',
            new_name='content',
        ),
    ]
